a=int(input('enter a number:'))
b=int(input('enter b number:'))
c=int(input('enter c number:'))
print('addition is:',a+b)
print('subtraction is:',a-b)
print('the result  of add ,sub mult is:',a+b*c)
print('the divison is :',b/a)
print('the modulation is:',b%a)
print('the floor division is:',c//a)
