a=int(input('enter the a variable:'))
b=int(input('enter the b variable:'))
print("sum of the two variable:",a+b)
print("subtraction of two variable:",a-b)
print("multiplication of two variable:",a*b)
print("power of two numbers:",a**b)
print("division of two numbers:",a/b)
print('floor divison of two numbers:',a//b)
print('modules of two numbers:',a%b)
